### ISSUE TITLE
Implementar modificações do glpi 9.4 no 9.5

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/formcreator#10]

**Comment by verdanatech-lucas** [comment]
Melhorias finalizadas, necessário teste formcreate na versão 9.5

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente.
![TesteFC](https://user-images.githubusercontent.com/80538863/128064487-560dbae9-b902-418f-9c9e-8e064da97e87.png)
