### ISSUE TITLE
GLPI 9.5 - Erro ao anexar arquivo

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/formcreator#12]
Já existe uma solução pronta : https://github.com/pluginsGLPI/formcreator/issues/1675

favor validar

**Comment by verdanatech-lucas** [comment]
Teste realizado, Anexo adicionado ao chamado utilizando o formcreator, segue imagem:
![image](https://user-images.githubusercontent.com/68446754/129027469-a7af5e20-db70-4883-a540-5d9fd883ce8c.png)
![image](https://user-images.githubusercontent.com/68446754/129028033-6401584f-8d70-4ada-942c-1dc75b5ef480.png)


A versão testada na solução é diferente daqui estamos utilizando nas 2 versões do glpi, as 2 que utilizamos são mais atuais

**Comment by verdanatech-lucas** [comment]
Teste realizado na versão 9.5, ao inserir a tag do arquivo na descrição o documento foi anexado ao chamado
![image](https://user-images.githubusercontent.com/68446754/129046223-51a3e58a-64dd-4e9d-8d8a-bbf9ebc89935.png)
