### ISSUE TITLE
GLPI 9.5 - Personalizar formulário anonimo 

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/formcreator#14]
Personalizar formulario anonimo

Pesquisar nos chamados 

Empresa CIASC

**Comment by verdanatech-lucas** [comment]
Implementação finalizada, segue imagem:
![image](https://user-images.githubusercontent.com/68446754/129214847-672cfc22-fa39-4efb-abfd-585c68917d1a.png)

Ao acessar formulário no modo anônimo, a imagem de background configurada no Skins é incluída como background da página do formulário

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente.
![TesteFC](https://user-images.githubusercontent.com/80538863/129727508-8ddc28f1-5404-4931-8424-6d8d691c8c23.png)
