### ISSUE TITLE
Implementar Modificações na Nova Versão do FormCreator

### ISSUE THREAD

**Issue by verdanatech-marcio** [verdanatech/formcreator#16]

**Comment by verdanatech-luana** [comment]
Teste executado criação, visualização e envio funcionando.
![2021-08-25_15-24](https://user-images.githubusercontent.com/86842154/130845516-2c9ea8e2-bc85-4b3a-ae24-221e824c250b.png)

**Comment by verdanatech-pereira** [comment]
Okay!
![image](https://user-images.githubusercontent.com/80539522/130850266-f3119a42-c47a-421e-b6cb-49d615dc6423.png)
![image](https://user-images.githubusercontent.com/80539522/130850296-c619f2b8-4b44-460b-9468-c4a217964f14.png)

**Comment by verdanatech-lucas** [comment]
Teste Realizado, css Correto, funcionalidades sem problemas também
![Captura de tela de 2021-08-30 08-28-15](https://user-images.githubusercontent.com/68446754/131332543-c2a4cfcc-6215-41b6-82b5-e152ff3d26f2.png)
