### ISSUE TITLE
Correção na pesquisa Faq

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/formcreator#2]
Não está realizando pesquisa

Provavelmente não está enviando o formulario de pesquisa para dentro do plugin

![image](https://user-images.githubusercontent.com/48805206/103218177-20d7c400-48f9-11eb-818a-7f14e339831c.png)

Para visualizar o funcionamento correto

![image](https://user-images.githubusercontent.com/48805206/103218937-20d8c380-48fb-11eb-8db0-5ed4aaf8e28d.png)

**Comment by verdanatech-lucas** [comment]
Issue finalizada, a biblioteca jstree foi incluída na página do form creator, segue imagem:
![image](https://user-images.githubusercontent.com/68446754/103235273-6bb90200-4920-11eb-92a9-4b8a1b211b9f.png)
