### ISSUE TITLE
Implementação - layout de cards faq

### ISSUE THREAD

**Issue by verdanatech-dev** [verdanatech/formcreator#24]
Adicionar descrição da faq no card

![image](https://user-images.githubusercontent.com/48805206/136278534-3e56d30f-679b-43eb-b7fc-6ff887478340.png)

**Comment by verdanatech-lucas** [comment]
Finalizado, foi implementado a exibição da descrição

**Comment by verdanatech-marcio** [comment]
Teste realizado, implementação correta.
![image](https://user-images.githubusercontent.com/80538863/146760956-3abe8e55-48be-484f-8970-a7f85411c1c6.png)
