### ISSUE TITLE
Verificar css alterado formcreator

### ISSUE THREAD

**Issue by verdanatech-marcio** [verdanatech/formcreator#26]

**Comment by verdanatech-marcio** [comment]
Testado, o css foi ajustado e o formulário anônimo foi corrigido. As seções estão juntas uma abaixo da outra e não ao lado mais.
![image](https://user-images.githubusercontent.com/80538863/140972726-4a4a0184-32b7-4f79-a20d-26010aaa1fdd.png)

**Comment by verdanatech-luana** [comment]
Seções alinhadas abaixo uma da outra 
![2021-11-11_15-42](https://user-images.githubusercontent.com/86842154/141351910-b43c94dc-f905-46bb-b555-260385607304.png)
